### ISSUE TITLE
[Bug Report] XML to USD possible load bug

### ISSUE THREAD

**Issue by giulioturrisi** [isaac-sim/IsaacLab#2147]
### Describe the bug

I'm trying to convert the following XML (https://github.com/iit-DLSLab/gym-quadruped/blob/master/gym_quadruped/robot_model/hyqreal/hyqreal.xml) in USD. With previous IsaacLab version, i was able to convert different model inside the same repo, but now, i obtain the following structure

![Image](https://github.com/user-attachments/assets/5f11a837-965c-42ed-a8bc-5ecd861ea89a)

As you can see, the "base" is duplicated, whereas with the old IsaacLab version i was able to convert the model in a structure like this:

![Image](https://github.com/user-attachments/assets/5f675ab8-7544-419c-8b92-b89e7fae400d)

Due to this difference, i cannot load correctly the usd in IsaacLab, since i obtain the following error:

AttributeError: 'Articulation' object has no attribute '_root_physx_view'

### System Info

- Commit: c4bec8f

Thanks

**Comment by Ycyofmine** [comment]
Solution for Ubuntu 22.04 users:
1. Delete the entire ov folder located at ~/.local/share/ov.  
2. Re-run the Isaac Sim selector script:  
```
./isaacsim-selector.sh
```
This should resolve the URDF import issue.

**Comment by yash-s20** [comment]
deleting worldBody from the USD fixes the error you're seeing (`no attribute _root_physx_view`) @giulioturrisi . it happens because the USD has multiple root prims (also discussed [here](https://forums.developer.nvidia.com/t/error-please-ensure-that-there-is-only-one-articulation-in-the-prim-path-tree/311183))

However I'm having issues loading multiple assets where only one responds to joint pose changes. Is this issue related @RandomOakForest ?

https://github.com/user-attachments/assets/a4d57f5c-08b0-4839-8295-c6260c5eaa1f

**Comment by louislelay** [comment]
Hi @RandomOakForest, I have the same issue as @giulioturrisi. And I wonder if that's why I have a problem with prim paths for sensors :

```
Traceback (most recent call last):
  File "/home/louislelay/Documents/pal_isaaclab/scripts/zero_agent.py", line 70, in <module>
    main()
  File "/home/louislelay/Documents/pal_isaaclab/scripts/zero_agent.py", line 48, in main
    env = gym.make(args_cli.task, cfg=env_cfg)
  File "/home/louislelay/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 742, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/envs/manager_based_rl_env.py", line 82, in __init__
    super().__init__(cfg=cfg)
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/envs/manager_based_env.py", line 157, in __init__
    self.sim.reset()
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/sim/simulation_context.py", line 536, in reset
    self.render()
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/sim/simulation_context.py", line 591, in render
    raise exception_to_raise
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/sensors/sensor_base.py", line 271, in _initialize_callback
    self._initialize_impl()
  File "/home/louislelay/Documents/IsaacLab/source/isaaclab/isaaclab/sensors/contact_sensor/contact_sensor.py", line 266, in _initialize_impl
    raise RuntimeError(
RuntimeError: Sensor at path '/World/envs/env_.*/Robot/.*' could not find any bodies with contact reporter API.
HINT: Make sure to enable 'activate_contact_sensors' in the corresponding asset spawn configuration.
```

I should mention that I've removed (deactivated) worldBody and although that solved a few errors, I still have this problem. And of course, activate_contact_sensors is already set to true.

**Comment by RandomOakForest** [comment]
Thank you for following up. We'll review and aim to resolve this soon.

**Comment by ooctipus** [comment]
xml to usd is currently a bit buggy, and urdf importer seems a lot more stabler, if it is possible, can you try to use urdf importer with isaaclab 2.1 + isaacsim 4.5 and see if it works?

**Comment by louislelay** [comment]
Hey @ooctipus, the URDF importer works perfectly but for a robot model we want to use, we only have a MJCF model. While we're currently working on converting it to URDF, the model is complicated and the conversion will take time. That's why we wanted to use the MJCF importer.

From what I've tested it seems to come from the MJCF importer extension of Isaac Sim, so I believe this issue could be closed here and a new one opened on the OSS repo (issue is still persisting in Isaac Sim 5.0.0).

**Comment by louislelay** [comment]
Hey @giulioturrisi, @yash-s20, and @ooctipus, I’ve just submitted a PR to the Isaac Sim MJCF importer extension that fixes this issue. Feel free to take a look and give it a try!

**Comment by giulioturrisi** [comment]
Great! I cannot find the link of the PR. Can you share it?

**Comment by louislelay** [comment]
It appears in the conversation just before my last comment, but here's the link anyway: https://github.com/isaac-sim/mjcf-importer-extension/pull/9

**Comment by ooctipus** [comment]
Thank you @louislelay  this is great!!, let me take a look : D

**Comment by giulioturrisi** [comment]
Unfortunately i cannot validate it, due to a build error of the mjcf-importer on ubuntu. Hopefully the others can do it.

**Comment by louislelay** [comment]
Hey @giulioturrisi! Could you try to build the MJCF importer with the main branch ? Just to see if it's an error that's happening only with my fix or not. And if not, please open an issue about it on the MJCF importer repo so I or others can try to look into it!

**Comment by giulioturrisi** [comment]
The error happens in the main branch as well. I will open an issue there!

EDIT: Issue here https://github.com/isaac-sim/mjcf-importer-extension/issues/10

**Comment by Kenjiro-Minamikawa** [comment]
> Hey [@giulioturrisi](https://github.com/giulioturrisi), [@yash-s20](https://github.com/yash-s20), and [@ooctipus](https://github.com/ooctipus), I’ve just submitted a PR to the Isaac Sim MJCF importer extension that fixes this issue. Feel free to take a look and give it a try!

Hi, I used this tool and it remove the worldBody. But the problem @yash-s20 mentioned is still remained.
Are there any idea to solve this problem?

**Comment by jgillick** [comment]
I found a workaround to this issue. I created my own version of the convert_mjcf.py script (see [original](https://github.com/isaac-sim/IsaacLab/blob/main/scripts/tools/convert_mjcf.py)), which removes the worldBody prim by deactivating it, flattening the USD, and then saving it.

You can see my version, here: https://github.com/jgillick/spider-bot/blob/2e49caa61fe957c0da25108770f72782b0a2b8f9/simulate/issac/mjcf_2_usd.py

I called it mjcf_2_usd.py and run it similarly to the original convert_mjcf script:

```
./isaaclab.sh -p ./scripts/tools/mjcf_2_usd.py <mujoco XML> <output USD>
```

**Comment by jgillick** [comment]
UPDATE: this comment is no longer accurate. The problem I'm describing was an issue with my model.

I've also noticed that when exporting from mujoco, the joints do not move -- even when following [the official example instructions](https://isaac-sim.github.io/IsaacLab/main/source/how-to/import_new_asset.html#id1) with an the recommended H1 mujoco model. From what I can tell, it's because the USD schema APIs are not setup correctly. They are using the `PhysicsDriveAPI:X` schema and attributes when they should be using `PhysicsDriveAPI:angular` (note `:X` and `:angular`).

I've made a post-export workaround in [this script](https://github.com/jgillick/spider-bot/blob/b3d70f15b0fcbc7ae0a13f575b31fb49c269e466/simulate/issac/tools/mjcf_2_usd.py).

**Comment by ooctipus** [comment]
@jgillick Thank you for providing the help! This bug should be fixed in the future release with update in IsaacSim:))

**Comment by louislelay** [comment]
Hi @ooctipus, if the bugs are going to be fixed in a future version of Isaac Sim does my PR to the MJCF importer extension still make sense ?

**Comment by jgillick** [comment]
FYI, [my comment](https://github.com/isaac-sim/IsaacLab/issues/2147#issuecomment-3092633674) seems to be wrong. My joints weren't moving because of another issue with my model.  My [original workaround](https://github.com/isaac-sim/IsaacLab/issues/2147#issuecomment-3072932364) is still valid, though.

**Comment by giulioturrisi** [comment]
Hello @ooctipus, i still have the problem describe in the first post here with IsaacLab v2.2.0 and IsaacSim5.0

Note that i can manage to rework the xml at my need only if i proceed importing the XML from IsaacSim graphic exporter

<img width="772" height="812" alt="Image" src="https://github.com/user-attachments/assets/85bc12fd-4816-4ad8-bffb-0502091a4958" />

**setting "Set as Deafult Primt" to False**

**Comment by ooctipus** [comment]
@giulioturrisi 
Interesting, thank you for looking into issue and try out different solutions.
can you describe in detail exactly what you need to rework in your xml in order to get is work? if you have the file that can share, maybe we can pass that to the sim team and make sure that gets fixed

**Comment by giulioturrisi** [comment]
Error from my side, the importer with Set as Default Prim to false, can make the object in the hierarchy movable but generate some problem, e.g.

<img width="640" height="400" alt="Image" src="https://github.com/user-attachments/assets/61828772-cb52-41ad-aee1-18d47860894b" />

Btw, for me the problem (as in the initial post) is the following: Looking at the USD inside IsaacSim, we have a structure like
- B2
- - base
- - hip
- - ....

<img width="640" height="400" alt="Image" src="https://github.com/user-attachments/assets/5181678a-d19c-4025-a20a-e5a0ee4dc759" />

But using the import (on any of the mujoco menagerie robot, e.g. https://github.com/google-deepmind/mujoco_menagerie/blob/main/unitree_a1/a1.xml), we have,
- A1
- - trunk
- - - trunk
- - - hip

<img width="588" height="417" alt="Image" src="https://github.com/user-attachments/assets/a5497a06-2e22-4b41-91cf-3ea54200760d" />

where there is an "extra layer" trunk (that is called base in the example of B2) that cannot be moved, and to be honest i don't get why this is generated looking at the xml of the robot.

**Comment by giulioturrisi** [comment]
Hello, i was able to load an xml by a mix of mujoco newton converter and manual procedure. The last is basically saving the .usda that mujoco newton converter create as **flattened**, and then moving manually the hierchachy using isaacsim.

I believe this could be made into a script, I can share more info if interested @ooctipus . My old policy works on the new asset.

**Comment by adrialopezescoriza** [comment]
Hello, I am using IsaacLab 5.1 and still experiencing the issue described here. Has a workaround been found?
