### ISSUE TITLE
[Bug Report] The training shut down for no reasons with 50 series card

### ISSUE THREAD

**Issue by 81578823** [isaac-sim/IsaacLab#2485]
The training shut down for no reasons with 50 series card  [bug].

### Describe the bug

The training shuts down for unknown reasons. 
```bash
[INFO]: Simulation is stopped. Shutting down the app.
```
### Steps to reproduce
```bash
python scripts/reinforcement_learning/rsl_rl/train.py --task=Isaac-Velocity-Rough-Anymal-B-v0 --headless
```
and 
```bash
python scripts/reinforcement_learning/rsl_rl/train.py --task=Isaac-Velocity-Rough-Anymal-C-v0 --headless
```

### System Info

- Isaac Sim Version: 4.5.0
- OS: Ubuntu 20.04
- GPU: RTX5080
- CUDA:12.8
- GPU Driver: 570.144
- torch: 2.7.0

**Comment by 81578823** [comment]
![Image](https://github.com/user-attachments/assets/a53a87c9-51c4-420b-9782-727191b0e6c0)

**Comment by 81578823** [comment]
Sometimes, it just gets stuck and does not move on

![Image](https://github.com/user-attachments/assets/906fa94c-2a63-48ad-9062-79deb03e8a4c)

**Comment by RandomOakForest** [comment]
Thank you for posting this, the team will review it.

**Comment by baijubaiju233** [comment]
Can you use the 50-series graphics cards for training? But when you open Isaac Sim 4.5 with a 50-series card, doesn't it blur objects? I think these two aren't compatible. I assumed that 50-series cards could only be used with Isaac Sim 5.0 paired with Isaac Lab 2.2. I’m really sorry for bringing up a topic unrelated to the issue, but I’m eager to know the answer.

**Comment by kellyguo11** [comment]
We have not been able to reproduce the initial issue, could you give the 5.0 Isaac Sim branch a try and see if you still observe it there?

Isaac Sim 4.5 will be able to run with 50-series cards, but there is a rendering issue that disables the denoiser, so rendered results will look very noisy. This has been fixed in Isaac Sim 5.0.

**Comment by 81578823** [comment]
@kellyguo11 Yes, now I am using 5.1.0 Isaacsim, 2.3.0 Isaaclab, 570 nvidia-driver, however, the interruption still happens without any error information or warning

**Comment by 81578823** [comment]
I have figured it out finally!!! The interruption occurs since I use intel_pstate driver for my cpu(Intel ultra 7-265K), which is the newest CPU hardware having compatibility issues with ubuntu.

The solutions are as follows:
- sudo gedit /etc/default/grub
- Change the line `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"` to `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=disable"` and save.
- sudo update-grub
- sudo reboot

After these operations, you can see the cpu driver has changed from `intel_pstate` to `acpi-cpufreq` according to `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver`.
The interruption does not occur any more.

ps: Do not forget to set CPU scaling_governor as `schedutil`, which will be better

**Comment by AntoineRichard** [comment]
@81578823 huge thanks for circling back with the root cause — most people never report what finally fixed it.

For anyone landing here later: this was the host's `intel_pstate` CPU-frequency driver on an Intel Ultra 7-265K, not Isaac Lab. Booting with `intel_pstate=disable` (falling back to `acpi-cpufreq`) plus the `schedutil` governor stopped the crashes. Since there's nothing to change on our side we're closing this — but please reopen if you see the same symptom on current hardware and releases.

---
*🤖 This issue was reviewed as part of an AI-assisted triage of the Isaac Lab backlog, with automated verification against the current codebase. If we got this wrong, please reopen — we'd rather hear about it!*
